//Getting cookie for size change from DOM.
const cookie = document.getElementById("cookie");
//Getting counter from DOM.
let counterSum = parseFloat(
  document.getElementById("clicker__avarage").textContent
);
//Get clicker counter form DOM.
let clicker = parseInt(document.getElementById("clicker__counter").textContent);

//Hidden tempo counter.
let tempoCounter = 0;

//Interval for ticks.
let interval = setInterval(
  (f = () => {
    tempoCounter += 1;
  }),
  1000
);

//Main onclick function.
cookie.onclick = () => {
  //Clearing interval on click.
  clearInterval(interval);
  //counterSum increasing on hiden tempoCounter, with ticks generated by intervals.
  counterSum += tempoCounter;
  //Reset counter for next click.
  tempoCounter = 0;
  //Clicker made for sendding into DOM.
  clicker += 1;
  //Avoiding deletion on zero.
  if (clicker != 0) {
    //Showing (updating) tempo in DOM.
    let result = (counterSum / clicker).toFixed(2);
    document.getElementById("clicker__avarage").textContent = result;
  }
  //Updating clicks in DOM.
  document.getElementById("clicker__counter").textContent = clicker;
  //Size change on cookie.
  if (cookie.width == 200) {
    cookie.width += 50;
  } else if (cookie.width == 250) {
    cookie.width -= 50;
  }
  //Reactivating interval for ticks.
  interval = setInterval(
    (f = () => {
      tempoCounter += 1;
    }),
    1000
  );
};
